#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
countMinutes()
{
	COUNT='0'
	while [ $COUNT -le 59 ]; do
		echo $COUNT
		((COUNT++))
	done	
}


countHours()
{
	local HOURS=$1
	COUNTHOUR='0'
	while [ $COUNTHOUR -le $HOURS ]; do
		echo "Hour: $COUNTHOUR"
		countMinutes
		((COUNTHOUR++))
	done
}

countHours '12'
